### PR TITLE
Add some more support for Huawei devices

### PR DESCRIPTION
**Pull request by robwwd**
Add support for more os version strings in SysDescr
Add support for Huawei hardware model

### CODE REVIEW

**Comment by JeroenvIS** [comment]
@robwwd Thanks for contributing.

I'm not sure if I'd want to merge this as-is though; generally we use vendor specific SNMP objects to report OS version and device model, where possible. That way we can report literally what the device itself indicates, without having to cull/interpret information from a generic object like sysDescr.

@jeneric What do you think?

**Comment by jeneric** [comment]
@JeroenvIS agree especially since it looks like models should be defined in the HUAWEI-MIB. A snmpwalk of target devices would be helpful.

**Comment by JeroenvIS** [comment]
From old snmpwalks collected at previous employer, using a S2700:

1) With correct MIBs loaded, full model is reported through sysObjectId.0:
SNMPv2-MIB::sysObjectID.0 = OID: HUAWEI-MIB::s2700-9TP-EI-AC

2) A relatively clean software version number seems to be available in HUAWEI-SYS-MAN-MIB::hwSysImageVersion:
HUAWEI-SYS-MAN-MIB::hwSysImageVersion.1 = STRING: S2700 V100R006C05

3) Maybe less useful, but for reference, file name for image:
HUAWEI-SYS-MAN-MIB::hwSysImageName.1 = STRING: S2700EI-V100R006C05.CC

4) Patch/hotfix info:
HUAWEI-SYS-MAN-MIB::hwSysCurPatchFileIndex.0 = INTEGER: 1
HUAWEI-SYS-MAN-MIB::hwSysReloadPatchFile.0 = INTEGER: 1
HUAWEI-SYS-MAN-MIB::hwSysReloadPatchState.0 = INTEGER: run(1)
HUAWEI-SYS-MAN-MIB::hwPatchFileNum.0 = INTEGER: 2
HUAWEI-SYS-MAN-MIB::hwPatchRecordReset.0 = INTEGER: unused(1)
HUAWEI-SYS-MAN-MIB::hwPatchHistoryTableMax.0 = INTEGER: 200
HUAWEI-SYS-MAN-MIB::hwPatchErrorTableMax.0 = INTEGER: 200
HUAWEI-SYS-MAN-MIB::hwPatchId.0 = STRING: 
HUAWEI-SYS-MAN-MIB::hwPatchLatestId.0 = STRING: 
HUAWEI-SYS-MAN-MIB::hwPatchFileName.1 = STRING: s2700_v100r006sph023.pat
HUAWEI-SYS-MAN-MIB::hwPatchFileName.2 = STRING: s2700_v100r006sph022.pat
HUAWEI-SYS-MAN-MIB::hwPatchFileSize.1 = INTEGER: 1274152
HUAWEI-SYS-MAN-MIB::hwPatchFileSize.2 = INTEGER: 1228732
HUAWEI-SYS-MAN-MIB::hwPatchFileLocation.1 = STRING: flash:/
HUAWEI-SYS-MAN-MIB::hwPatchFileLocation.2 = STRING: flash:/
HUAWEI-SYS-MAN-MIB::hwPatchFileVersion.1 = STRING: V100R006SPH023
HUAWEI-SYS-MAN-MIB::hwPatchFileVersion.2 = STRING: V100R006SPH022
HUAWEI-SYS-MAN-MIB::hwPatchUsedFileName.0.167 = STRING: flash:/s2700_v100r006sph023.pat
HUAWEI-SYS-MAN-MIB::hwPatchVersion.0.167 = STRING: V100R006SPH023
HUAWEI-SYS-MAN-MIB::hwPatchDescription.0.167 = STRING: 
HUAWEI-SYS-MAN-MIB::hwPatchProgramVersion.0.167 = STRING: S2700 V100R006C05
HUAWEI-SYS-MAN-MIB::hwPatchFuncNum.0.167 = INTEGER: 0
HUAWEI-SYS-MAN-MIB::hwPatchTextLen.0.167 = INTEGER: 0
HUAWEI-SYS-MAN-MIB::hwPatchDataLen.0.167 = INTEGER: 0
HUAWEI-SYS-MAN-MIB::hwPatchType.0.167 = INTEGER: hotCommon(1)
HUAWEI-SYS-MAN-MIB::hwPatchBuildTime.0.167 = STRING: 0-0-0,0:0:0.0
HUAWEI-SYS-MAN-MIB::hwPatchActiveTime.0.167 = STRING: 0-0-0,0:0:0.0
HUAWEI-SYS-MAN-MIB::hwPatchAdminStatus.0.167 = INTEGER: run(1)
HUAWEI-SYS-MAN-MIB::hwPatchOperateState.0.167 = INTEGER: patchRunning(1)
HUAWEI-SYS-MAN-MIB::hwPatchOperateDestType.0.167 = INTEGER: unused(5)
HUAWEI-SYS-MAN-MIB::hwPatchOperateDestIndex.0.167 = STRING: unused
HUAWEI-SYS-MAN-MIB::hwPatchNumMax.0 = Gauge32: 167
HUAWEI-SYS-MAN-MIB::hwPatchIdleNum.0 = INTEGER: 233
HUAWEI-SYS-MAN-MIB::hwPatchTextMax.0 = INTEGER: 0
HUAWEI-SYS-MAN-MIB::hwPatchDataMax.0 = INTEGER: 0
HUAWEI-SYS-MAN-MIB::hwPatchStateTextUsed.0 = INTEGER: 0
HUAWEI-SYS-MAN-MIB::hwPatchStateDataUsed.0 = INTEGER: 0
HUAWEI-SYS-MAN-MIB::hwPatchStateTotalPatchNum.0 = INTEGER: 0
HUAWEI-SYS-MAN-MIB::hwPatchStateTempPatchNum.0 = INTEGER: 0
HUAWEI-SYS-MAN-MIB::hwPatchStateCommonPatchNum.0 = INTEGER: 0
HUAWEI-SYS-MAN-MIB::hwPatchStateRuningPatchNum.0 = INTEGER: 167
HUAWEI-SYS-MAN-MIB::hwPatchStateActivePatchNum.0 = INTEGER: 0
HUAWEI-SYS-MAN-MIB::hwPatchStateDeactivePatchNum.0 = INTEGER: 0

**Comment by robwwd** [comment]
I used the sysdescr in this case from the estate of Huawei routers we have are rather old CPE type devices.

```
snmpget -v 2c -c XXXX 1.1.1.1 HUAWEI-SYS-MAN-MIB::hwSysImageVersion.1
HUAWEI-SYS-MAN-MIB::hwSysImageVersion.1 = No Such Object available on this agent at this OID
```

```
snmpwalk -v 2c -c XXX 1.1.1.1 1.3.6.1.4.1.2011.5.25.19.1.4.2.1
HUAWEI-MIB::hwDatacomm.19.1.4.2.1 = No Such Object available on this agent at this OID

```
SNMP::Info::device_type() layers:01001110 id:2011 sysDescr:"Huawei Versatile Routing Platform Software VRP Software Version 3.40, Release 0311P07 Quidway Series Router AR28-31 Copyright (c) 1998-2011, Huawei Technologies Co., Ltd. All rights reserved. "

Above is the sysDescr for that device.

Same for some other devices we have:

SNMP::Info::device_type() layers:01001110 id:2011 sysDescr:"Huawei Versatile Routing Platform Software VRP Software Version 3.40, Feature 0308 Quidway Series Router AR46-40 Copyright (c) 1998-2007, Huawei Technologies Co., Ltd. All rights reserved. "

SNMP::Info::device_type() layers:01001110 id:2011 sysDescr:"Huawei Versatile Routing Platform Software,VRP software, Version 3.40, Feature 0121L01.Quidway Router AR18-34E.Copyright (c) 1998-2009 Huawei Technologies Co., Ltd. All rights reserved."

SNMP::Info::device_type() layers:01001110 id:2011 sysDescr:"Huawei AR151 Huawei Versatile Routing Platform Software  VRP (R) software,Version 5.120 (AR151 V200R003C01SPC100) Copyright (C) 2011-2013 Huawei Technologies Co., Ltd"

One of the newer CPE we have does work. This is a much newer (relative to the others) platform and OS.

```
snmpget -v 2c -c XXXXX 2.2.2.2 HUAWEI-SYS-MAN-MIB::hwSysImageVersion.1
HUAWEI-SYS-MAN-MIB::hwSysImageVersion.1 = STRING: V200R003C01SPC100
```

However the system image is not meaningful as it does not corresponding to the VRP version I'm after.

```
<CPE>display version
Huawei Versatile Routing Platform Software
VRP (R) software, Version 5.120 (AR150 V200R003C01SPC100)
Copyright (C) 2011-2013 HUAWEI TECH CO., LTD

```

`SNMP::Info::device_type() layers:01001110 id:2011 sysDescr:"Huawei AR151 Huawei Versatile Routing Platform Software  VRP (R) software,Version 5.120 (AR151 V200R003C01SPC100) Copyright (C) 2011-2013 Huawei Technologies Co., Ltd"`

But most of our devices are are somewhat old but need to be supported by us as they are still being used by our customers. For me I would have to relying on parsing the sysDescr to get the version and model.

**Comment by jeneric** [comment]
I'm not going to merge this pull request, however, commit f2fdbb077c5f0a1fe118583db4f402f97d57bb91 has a different implementation of your suggestion for os_ver. The test class incorporates all the strings you provided. Pulling from the ENTITY-MIB also provides the information you needed in all the models  observed. The model uses the MIB which have been updated and had entries for all the models that you provided strings for.

**Pull request closed without merging**
