### PR TITLE
Whiterabbit

### PR DESCRIPTION
**Pull request by fragfutter**
Add support for whiterabbit (precision timing) switches
https://ohwr.org/projects/white-rabbit

### CODE REVIEW

**Comment by inphobia** [comment]
since the cern / whiterabbit mibs were added after netdisco-mibs 4.019 was released we need to do a new mib release first. i'm trying to get that done in the next 10 days,

**Comment by inphobia** [comment]
netdisco-mibs 4.020 has been released with these mibs included

**Comment by fragfutter** [comment]
Now that the mibs are in netwdisco-mibs, can we get this merged?

**Comment by inphobia** [comment]
yup, i think we're almost good to go.

i removed the references to s::i::lldp & s::i::bridge since they'll get pulled in via s::i::layer3. (a lot of modules do indeed have both layer3 & lldp, this was from before lldp was included in layer3). the only reason to include those modules seperatly is when the loading order is important, which is seldom the case.

could you test with these chances & then i'll commit.

**Comment by fragfutter** [comment]
a quick test showed no problems.

**Comment by inphobia** [comment]
quick note. i haven't forgotten this. do expect it to take a few weeks to get this merged due to personal time constraints (& we still need to migrate snmp::info away from travis-ci.org)

**Pull request merged**
