### PR TITLE
Support Siemens Scalance Switch

### PR DESCRIPTION
**Pull request by fragfutter**
This is a hackish support for siemens scalance switches 

  * workaround for missing lldp remote ip addresses.
  * overwrite layers capabilities
  * shorten interface descriptions

This is my first perl code for ages. Please comment if anything is not "perlish".

I added Scalance at two places in Info.pm. For layer3 and for unknown layers. Otherwise it would somehow flip/flop

### CODE REVIEW

**Comment by inphobia** [comment]
heya, first of thx for the patch!

iirc this was first submitted as a layer2 module. it seems that during the conversion you might have missed changing the includes to layer3 as well, since the module seems to use layer2 as base.

while i never considered using munge to change os_ver or i_description i have to say this is an interesting approach, but most modules just overwrite those functions instead. i think the cleanest example of this is:
https://github.com/netdisco/snmp-info/blob/6d39026616ab99a1d82fed6e4c08fd55bda890a8/lib/SNMP/Info/Layer3/Netscreen.pm#L233-L238
any reason to use munge instead of overwriting the function (other than the fact that our docs could be clearer perhaps 😄 )

finally, but not enforced, if you could also add a test for this module that would be cool. there are plenty of examples here:
https://github.com/netdisco/snmp-info/tree/master/xt/lib/Test/SNMP/Info

let us know if you have any more questions, or join us on irc. should be merged pretty soon.

**Comment by fragfutter** [comment]
munge looked natural for me. No calls to super, no looping. 

replaced munges with overwrites
switch to layer3 base class
wrote test case (hope it makes sense)

unit tests should work once mibs are updated.

**Comment by inphobia** [comment]
seems fine to me. i'll add a note that this is waiting on either:

netdisco/netdisco-mibs#100 -> has a few unexpected changes in reports/all to ospf stuff

or

netdisco/netdisco-mibs#97 -> somehow seems to have rewritten most of reports/all.

**Comment by inphobia** [comment]
mibs have been imported, i'll review this asap (wish there was a way to retrigger travis checks)

**Comment by inphobia** [comment]
also released a new version (4.018) of netdisco-mibs with siemens included and updated snmp::info travis config.

**Comment by fragfutter** [comment]
travis config is still on netdisco-mibs 4.017

**Pull request merged**
