### PR TITLE
Add travis file

### PR DESCRIPTION
**Pull request by djzort**
Net-SNMP must be compiled from scratch as the ubuntu one is linked
against system perl.

Also the shrlplib is needed for now, else net-snmp doesnt compile

### CODE REVIEW

**Comment by djzort** [comment]
net-snmp was a pita to get going in travis.

**Comment by abraxxa** [comment]
I can help with Net-SNMP compilation on Ubuntu as I've gone through this pain on 16.10 just two weeks ago with Perl 5.24.1 which requires patches from Debian not upstreamed so far. They are in 17.04 as Ubuntu updated system Perl to 5.24.

**Comment by djzort** [comment]
please fork my fork and show me the way

**Comment by abraxxa** [comment]
Sorry for the late reply!
Basically it boils down to:

- checkout the source package of net-snmp: `apt-get source net-snmp`
- in case of Perl 5.024 additional patches are required that are in Ubuntu 17.04 but not in 16.10, same for Debian 8:
    - this lists the two applied patches: http://changelogs.ubuntu.com/changelogs/pool/main/n/net-snmp/net-snmp_5.7.3+dfsg-1ubuntu5/changelog
    - Makefile bug report: https://sourceforge.net/p/net-snmp/bugs/2712/
    - Debian bug report with patch files for both: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825014
- after those are applied using patch -u < $filename (which doesn't hurt on Perl < 5.024 as at least the Makefile one is a bug only triggered by 5.024 but could happen on lower versions as well) you still need to fix that configure doesn't pick up the system Perl.
- I've done that by renaming /usr/include/net-snmp and creating a symlink to the patched version

As I made the mistake of not writing everything down when I encountered and fixed the problem I'm pretty sure some things are missing. As Ubuntu 17.04 will be out soon I won't have to care about this issue on my notebook again, same for Debian 9 which should be out this year for servers.

If you can't get it to work for Travis get back to me!

**Comment by djzort** [comment]
This PR has Travis working.

**Comment by ollyg** [comment]
This PR seems to patch SNMP::Info to use Dist:::Zilla which I don't think we can accept. I may try to get the Travis build working with our Build.PL if we can, and if I find the time. Otherwise I would appreciate another try using Build.PL! Thanks :)

**Comment by ollyg** [comment]
Hi there! We now have a working Travis CI test running for SNMP::Info:
https://travis-ci.org/netdisco/snmp-info

Although the config I ended up implementing in the end is very different to the patch here, I did take many ideas from it, so I am extremely grateful for you kickstarting the work (and helping when I was stuck). thank you!

**Pull request closed without merging**
