### PR TITLE
 Retrieve Serial Number and device type for CheckPoint 

### PR DESCRIPTION
**Pull request by earendilfr**
I have tried, as requested in previous PR, to update the xt/ file.
Could you check?

### CODE REVIEW

**Comment by inphobia** [comment]
seems to be a quite complete diff, i'll try & make some time asap to get this merged.

**Comment by inphobia** [comment]
i'm back in the land of the living, expect it to get imported in the next few days.

**Comment by inphobia** [comment]
seems fine to me.

1 final question: only 3 snmp::info modules seem to use dynamic vendor names, all others have it hardcoded. are there multiple vendor names in use for these devices or do they always return `checkpoint`?

**Comment by inphobia** [comment]
i'll already commit this, but will change the vendor function to return lowercase info only, like all the others.

**Comment by inphobia** [comment]
also, thx for the support!

**Comment by inphobia** [comment]
side note: the snmp.conf configuration needed for checkpoint, is that for ipso based devices only?

tbh, glad i'm no longer on that nokia ip350 & checkpoint ng fp3 :)

**Comment by earendilfr** [comment]
OK for the vendor option: you're right if all module return static value.
For the snmp.conf: yes, some old Checkpoint device (not remember which them) return only values to identify them as Linux server.
So, this option provide a solution to have the good type of information (but clearly, the SNMP OID provide by Checkpoint is the best solution).

**Pull request merged**
