### PR TITLE
UBNT adjustments - Add ER-12

### PR DESCRIPTION
**Pull request by LBegnaud**
I've made these adjustments and implemented in our environment of 500+ devices. I'm making the PR to not forget about it, but maybe best to wait a day or 2 to make sure the changes are stable (as minor as they are)

### CODE REVIEW

**Comment by LBegnaud** [comment]
Seems to be working just fine in our environment

**Comment by inphobia** [comment]
changing vendor to lowercase fixed travis issue.

i'm also a proponent of changing osname/whatever to lowercase.  but perhaps that should be handled in a different ticket.

**Comment by inphobia** [comment]
merging this for now so we don't forget about this, but ubiquiti seems to have expanded into switches & routers as well.

so in the future this class will either needs to be expanded or split into different ones (wifi/switch/router).

**Comment by LBegnaud** [comment]
@inphobia fyi this does include the ubnt edge router (ER) and edge switch (ES) lines, as well as unifi AP and ubnt wifi bridge.

We don't run any unifi switches or routers though, so I don't know what those would report (or even if they use the same vendor oid)

**Comment by inphobia** [comment]
i noticed, but looking at the current code it might be better to try & split them up into access points & routers/switches.

mostly since the current codeline uses 802dot11 functions which don't really have a place here i think. device type override like the ones here:
https://github.com/netdisco/snmp-info/blob/50841b51094084dceee406b69d56fbf2a415b10d/lib/SNMP/Info.pm#L1801

could get us out of that mess, but that someone would need to whip up a edgerouter&switch module. having no mibs that i can find doesn't help much either...

**Comment by LBegnaud** [comment]
yea i recall asking about organization and didn't get an answer. I'm up for whatever you want as far as restructuring it goes. If you want me to test any of the changes i'm more than happy, we have a huge array of UBNT network products really

**Pull request merged**
