### PR TITLE
Add initial support for Teltonika RUT9xx routers

### PR DESCRIPTION
**Pull request by JeroenvIS**
Squashed version of previous branch with a couple of improvements. New PR so Travis will also test.

### CODE REVIEW

**Comment by JeroenvIS** [comment]
@ollyg and @inphobia : care for a quick review?

**Comment by inphobia** [comment]
while i haven't checked in depth, i do have some semi related comments:
```
'UCD-SNMP-MIB'        => 'versionTag',
'NET-SNMP-TC'         => 'netSnmpAliasDomain',
'HOST-RESOURCES-MIB'  => 'hrSystem',
```
these are alrdy used in 4/5 l3 modules: checkpoint, netsnmp, cumulus, mikrotik & packetfront.
perhaps we whould move these to layer3.pm, or would that create to much overhead?

since the teltonika mibs have alrdy been added, couldn't we use more of their specific oids?
most obvious would be:
 * `'rut_serial'     => '.1.3.6.1.4.1.48690.1.5.0',` -> https://github.com/netdisco/netdisco-mibs/blob/9ff669c8dbe6f3e814997195898b9bea01cec14e/teltonika/TLT-MIB_RUT9XX.txt#L64

i guess there's a reason why you used the numeric id for that, and i'm not about to argue with the snmp guru snmp::info internals. :)

**Comment by inphobia** [comment]
since these are routers i guess they have layer2 & 3 support?
if so it would be best practice to add their enterprise oid to the l2 & l3 oid maps. that should be in these 2:

https://github.com/netdisco/snmp-info/blob/543072ca259a21c7f9f3f852b6b6df9f7acbbfb8/lib/SNMP/Info.pm#L1665
https://github.com/netdisco/snmp-info/blob/543072ca259a21c7f9f3f852b6b6df9f7acbbfb8/lib/SNMP/Info.pm#L1728


also, even the most basic testfile under https://github.com/netdisco/snmp-info/tree/master/xt/lib/Test/SNMP/Info would be welcome. since there aren't a lot of functions or exceptions i think you can just copy another basic test there & fill in the correct values. if you lack the time for that i think i can whip up a testfile if you provide me with the basic snmpwalk output.

**Comment by JeroenvIS** [comment]
> while i haven't checked in depth, i do have some semi related comments:
> 
> ```
> 'UCD-SNMP-MIB'        => 'versionTag',
> 'NET-SNMP-TC'         => 'netSnmpAliasDomain',
> 'HOST-RESOURCES-MIB'  => 'hrSystem',
> ```
> 
> these are alrdy used in 4/5 l3 modules: checkpoint, netsnmp, cumulus, mikrotik & packetfront.
> perhaps we whould move these to layer3.pm, or would that create to much overhead?

They are generally included for devices that base their SNMP agent support on the net-snmp code, as far as I know - often having at least some degree of Linux under the hood. I wouldn't add them to Layer3.pm because they often won't be supported by SNMP agents from different origins.

> since the teltonika mibs have alrdy been added, couldn't we use more of their specific oids?
> most obvious would be:
> 
>     * `'rut_serial'     => '.1.3.6.1.4.1.48690.1.5.0',` -> https://github.com/netdisco/netdisco-mibs/blob/9ff669c8dbe6f3e814997195898b9bea01cec14e/teltonika/TLT-MIB_RUT9XX.txt#L64
> 
> 
> i guess there's a reason why you used the numeric id for that, and i'm not about to argue with the snmp guru snmp::info internals. :)

Ah, yes, good one. This was still somewhat in flux, I probably hard-coded the OID earlier because the MIB wasn't loaded, but that was because my module wasn't even loaded (I think).

Will double check and improve if possible.

**Comment by JeroenvIS** [comment]
> > since the teltonika mibs have alrdy been added, couldn't we use more of their specific oids?
> > most obvious would be:
> > ```
> > * `'rut_serial'     => '.1.3.6.1.4.1.48690.1.5.0',` -> https://github.com/netdisco/netdisco-mibs/blob/9ff669c8dbe6f3e814997195898b9bea01cec14e/teltonika/TLT-MIB_RUT9XX.txt#L64
> > ```
> > 
> > 
> > i guess there's a reason why you used the numeric id for that, and i'm not about to argue with the snmp guru snmp::info internals. :)
> 
> Ah, yes, good one. This was still somewhat in flux, I probably hard-coded the OID earlier because the MIB wasn't loaded, but that was because my module wasn't even loaded (I think).
> 
> Will double check and improve if possible.

Found it: the literal leaf name for that object is 'serial' and I got into a name => oid resolving issue because of that. Without this mapping and override, 'serial' got translated to 'serial1' which then mapped to a Cisco object.

However, adding a mapping from 'serial1' to 'serial' in %GLOBALS fixes this, so I can leave out the literal OID and the 'serial' function.

**Comment by inphobia** [comment]
> > while i haven't checked in depth, i do have some semi related comments:
> > ```
> > 'UCD-SNMP-MIB'        => 'versionTag',
> > 'NET-SNMP-TC'         => 'netSnmpAliasDomain',
> > 'HOST-RESOURCES-MIB'  => 'hrSystem',
> > ```
> > 
> > 
> > these are alrdy used in 4/5 l3 modules: checkpoint, netsnmp, cumulus, mikrotik & packetfront.
> > perhaps we whould move these to layer3.pm, or would that create to much overhead?
> 
> They are generally included for devices that base their SNMP agent support on the net-snmp code, as far as I know - often having at least some degree of Linux under the hood. I wouldn't add them to Layer3.pm because they often won't be supported by SNMP agents from different origins.

hm, hadn't really considered that perspective. perhaps it's best to leave it alone.

**Review by inphobia — APPROVED** [review]
seems ready to be merged.

:thumbsup:

**Comment by JeroenvIS** [comment]
Woop woop! Thx @inphobia

**Pull request merged**
