### PR TITLE
Create DLink.pm

### PR DESCRIPTION
**Pull request by Krakozaber**
Create DLink class for https://github.com/netdisco/netdisco-mibs/issues/18

### CODE REVIEW

**Comment by ollyg** [comment]
Hi Petrov - looks good, are you ready for us to merge? Thanks!

**Comment by Krakozaber** [comment]
I think yes. But I hope that this is not the end... :-)

**Comment by Krakozaber** [comment]
I think now is all.

**Comment by ollyg** [comment]
Thank you again!

**Pull request merged**
